apiVersion: app/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app.kubernetes.io/name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opa
    spec:
      containers:
      - args:
        - "run"
        - "--server"
        - "--log-level=debug"
        #- "--set=decision_logs.console=true"
        - "--log-format=text"
        - "--addr=0.0.0.0:8181"
        - "--config-file=/etc/opa_config/config.yaml"
        image: openpolicyagent/opa:0.18.0
        imagePullPolicy: Always
        name: opa
        volumeMounts:
        - mountPath: "/etc/opa_config/"
          name: config
      volumes:
      - name: config
        configMap:
          name: opa-config