# Default values for htcondor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

condorHost:
ccbHost:
proxyCacheHost:
proxyCachePort: 30080

htcMaster:
  enabled: true
  image: dodasts/htcondor
  tag: fermi
  pullPolicy: IfNotPresent
  replicas: 1
  networkInterface: ""
  nodeSelector: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: condor
            operator: In
            values:
            - ccb
  # TODO: implement configMap for configuring each daemon

htcSchedd:
  enabled: true
  image: dodasts/htcondor
  tag: fermi
  pullPolicy: IfNotPresent
  replicas: 1
  networkInterface: ""
  lowPort: 31024
  highPort: 32048
  nodeSelector: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: condor
            operator: In
            values:
            - schedd
  persistence:
    enabled: true
    size: 5Gi
    claimSize: 4Gi
    storageClass: local-storage
    mountPath: /var/lib/condor/spool/
    options: |
      local:
        path: " /tmp/"
      nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: condor
              operator: In
              values:
              - schedd
  # TODO: implement configMap for mapfile
  # TODO: get rid of ttscache with secrets

htcWn:
  image: dodasts/htcondor
  tag: fermi
  pullPolicy: IfNotPresent
  replicas: 1
  cpu:
    request: 1
    limit: 1.5
  ram:
    request: 2048Mi
    limit: 2500Mi
  slotType: cpus=1, mem=2000
  nodeSelector: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: condor
            operator: NotIn
            values:
            - ccb
            - schedd

ttsCache:
  enabled: true
  image: dodasts/ttscache
  tag: v1.1.0-dodas
  pullPolicy: IfNotPresent
  replicas: 1
  iamToken:
  iamClientId:
  iamClientSecret:
  iamScimClientId:
  iamScimSecret:
  iamMapGroup: ALL
  proxyAudience: "https://dodas-tts.cloud.cnaf.infn.it"
  proxyTTS: "https://dodas-tts.cloud.cnaf.infn.it"
  proxyIAMEndpoint: "https://dodas-iam.cloud.cnaf.infn.it/"
  proxyCredentialEndpoint: "https://dodas-tts.cloud.cnaf.infn.it/api/v2/iam/credential"

nfs:
  enabled: false
  size: 1Gi
  claimSize: 950Mi
  server: DUMMY
  path: "/"

cvmfs:
  enabled: false
  image: cloudpg/cvmfs
  tag: k8s
  pullPolicy: IfNotPresent
  replicas: 1
  repoList: cms.cern.ch oasis.cern.ch
  defaultLocalConfig: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3

