{{- if .Values.ingress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jhubaas
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # comment this to use your own certs
    cert-manager.io/issuer: "jhub-self-issuer"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port:
                  name: http
      host: {{ .Values.hostname }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: jhub-tls
{{- end }}