{{- if .Values.cvmfs.enabled -}}
# TODO configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-local
data:
  default.local: {{ .Values.cvmfs.defaultLocalConfig }}
  # other file: put here
---

{{- if .Values.cvmfs.privKey }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData: {{ .Values.cvmfs.privKey }}
{{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvmfs
  labels:
    app.kubernetes.io/name: cvmfs-pod
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cvmfs
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cvmfs
{{- if .Values.htcWn.nodeSelector }}
{{ .Values.htcWn.nodeSelector | indent 8 }}
{{- end }}
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: cvmfs
        image: "{{ .Values.cvmfs.image }}:{{ .Values.cvmfs.tag }}"
        imagePullPolicy: {{ .Values.cvmfs.pullPolicy }}
        env:
        - name: REPO_LIST
          value:   "{{ .Values.cvmfs.repoList }}"
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - mountPath: "/cvmfs"
          name: cvmfs
          mountPropagation: Bidirectional
        - mountPath: "/etc/cvmfs/"
          name: default-local
        - mountPath: "/etc/cvmfs/keys"
          name: privKeys
      restartPolicy: Always
      volumes:
      - name: cvmfs
        hostPath:
          path: "/cvmfs"
          type: Directory
      - name: default-local
        configMap: 
          name: default-local
      {{- if .Values.cvmfs.privKey }}
      - name: privKeys
        configMap: 
          secret:
            secretName: secrets
            defaultMode: 256
      {{- end}}
        # TODO CONFIGMAP
  selector:
    matchLabels:
      app.kubernetes.io/name: cvmfs
  replicas: {{ .Values.cvmfs.replicas }}
{{- end }}
