apiVersion: apps/v1
kind: Deployment
metadata:
  name: wn-pod
  labels:
    app.kubernetes.io/name: wn-pod
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wn
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
      affinity:
{{- if .Values.htcWn.nodeSelector }}
{{ .Values.htcWn.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - name: wn
        imagePullPolicy: {{ .Values.htcWn.pullPolicy }}
        args:
        - wn 
        env:
        - name: CONDOR_HOST 
          value: "{{ .Values.condorHost }}"
        - name: PROXY_CACHE 
          value: "{{ .Values.proxyCacheHost }}:{{ .Values.proxyCachePort }}"
        - name: CCB_ADDRESS
          value:  "{{ .Values.ccbHost }}"
        - name: SLOT_TYPE_1
          value: "{{ .Values.htcWn.slotType }}"

        image: "{{ .Values.htcWn.image }}:{{ .Values.htcWn.tag }}"
        livenessProbe:
          exec:
            command:
            - voms-proxy-info
            - --file
            - /root/gwms_proxy
            - --exists
          initialDelaySeconds: 300
          periodSeconds: 600
        resources:
          limits:
            memory: "{{ .Values.htcWn.ram.limit }}"
            cpu: "{{ .Values.htcWn.cpu.limit }}"
          requests: 
            memory: "{{ .Values.htcWn.ram.request }}"
            cpu: "{{ .Values.htcWn.cpu.request }}"
        volumeMounts:
{{- if .Values.nfs.enabled -}}
        - name: nfs
          mountPath: "/mnt"
{{- end }}
{{- if .Values.cvmfs.enabled -}}
        - name: cvmfs
          mountPath: "/cvmfs"
{{- end }}

      volumes:
{{- if .Values.nfs.enabled -}}
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
{{- end }}
{{- if .Values.cvmfs.enabled -}}
      - name: cvmfs
        hostPath:
          path: /cvmfs
          type: Directory
{{- end }}

  selector:
    matchLabels:
      app.kubernetes.io/name: wn 

  replicas: {{ .Values.htcWn.replicas }}
