{{- if .Values.htcWn.siteConfCMS.enabled }}
{{- range  .Values.htcWn.siteConfCMS.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }} 
data:
{{ .filename | indent 2 }}: |
{{ .content | indent 4 }}

---

{{- end }}

{{- end }}