{{- if .Values.ttsCache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-pod
  labels:
    app.kubernetes.io/name: tts-pod
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tts
    spec: 
      affinity:
{{- if .Values.htcMaster.nodeSelector }}
{{ .Values.htcMaster.nodeSelector | indent 8 }}
{{- end }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers: 
      - name: tts-cache
        imagePullPolicy: "{{ .Values.ttsCache.pullPolicy }}"
        env: 
        - name: IAM_TOKEN
          value:  "{{ .Values.ttsCache.iamToken }}"
        - name: IAM_CLIENT_ID
          value: "{{ .Values.ttsCache.iamClientId }}"
        - name: IAM_CLIENT_SECRET
          value: "{{ .Values.ttsCache.iamClientSecret }}"
        - name: IAM_MAP_CLIENT_ID
          value: "{{ .Values.ttsCache.iamScimClientId }}"
        - name: IAM_MAP_CLIENT_SECRET
          value: "{{ .Values.ttsCache.iamScimSecret }}"
        - name: IAM_MAP_GROUP
          value: "{{ .Values.ttsCache.iamScimGroup }}"
        - name: PROXY_AUDIENCE
          value:  "{{ .Values.ttsCache.proxyAudience }}"
        - name: PROXY_TTS
          value: "{{ .Values.ttsCache.proxyTTS }}"
        - name: PROXY_IAM_ENDPOINT
          value:  "{{ .Values.ttsCache.proxyIAMEndpoint }}"
        - name: PROXY_CREDENTIAL_ENDPOINT
          value: "{{ .Values.ttsCache.proxyCredentialEndpoint }}"
        - name: PROXY_LOCAL_CACHE_EXPIRATION_TIME
          value: "86400"
        - name: PROXY_LOCK_FILE_AGE
          value: "20"
        - name: PROXY_CACHE_DIR
          value: "/tmp"
        image:  "{{ .Values.ttsCache.image }}:{{ .Values.ttsCache.tag }}"
        livenessProbe:
          exec:
            command:
            - voms-proxy-info
            - --file
            - /tmp/userproxy.pem
            - --valid
          initialDelaySeconds: 300
          periodSeconds: 600
        volumeMounts:
        - mountPath: "/tmp"
          name: temp
      volumes:
      - name: temp
        hostPath:
          path: /tmp
  selector:
    matchLabels:
      app.kubernetes.io/name: tts

  replicas: 1
{{- end }}