{{- if and .Values.gsi.cacheCert.cert  .Values.gsi.cacheCert.key }}
apiVersion: v1
kind: Secret
metadata:
  name: certs
type: Opaque
stringData:
  cert.pem: {{ .Values.gsi.cacheCert.cert }}
  key.pem: {{ .Values.gsi.cacheCert.key     }}
{{- end }}