annotations:
  category: stable
apiVersion: v1
name: Fermi-experiment
version: 0.0.5
appVersion: 8.9.3
description: HTCondor pool for Fermi experiment
keywords:
- ams
- htcondor
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Fermi_Gamma-ray_Space_Telescope_logo.svg/1172px-Fermi_Gamma-ray_Space_Telescope_logo.svg.png
maintainers:
- name: dciangot
  email: diego.ciangottini@pg.infn.it
