# -v $PWD/traefik.yml:/etc/traefik/traefik.yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: traefikconfig
data:
  traefik.yaml: |
    providers:
      redis:
        endpoints:
        - "127.0.0.1:6379"
    entryPoints:
      tcp:
        address: ":3443/tcp"
    log:
      level: DEBUG