apiVersion: v1 
kind: Service 
metadata:
  name: traefik 
spec:
  type: ClusterIP 
  ports:
    - targetPort: 3443 
      protocol: TCP
      name: traefik 
  selector:
    app.kubernetes.io/name: daskssh