apiVersion: v1 
kind: Service 
metadata:
  name: listener 
spec:
  type: ClusterIP 
  clusterIP: 
  ports:
    - port: 8122 
      targetPort: 8122
      protocol: TCP
      name: listener 
  selector:
    app.kubernetes.io/name: daskssh
