apiVersion: v1 
kind: Service 
metadata:
  name: daskssh 
spec:
  type: NodePort 
  ports:
    - port: 8022 
      nodePort: {{ .Values.daskssh.nodePort }}
      protocol: TCP
      name: daskssh 
  selector:
    app.kubernetes.io/name: daskssh 
