hostname: jhub.<PUT PUBLIC HOST>
jupyterhub:
  ingress:
    enabled: true
    # annotations:
    #   kubernetes.io/ingress.class: "nginx"
    #   # comment this to use your own certs
    #   #cert-manager.io/issuer: "selfsigned-issuer"
    # hosts:
    #   - {{ .Values.hostname }}
    # tls:
    #   - hosts:
    #     - {{ .Values.hostname }}
    #     secretName: jhub-tls
    #     # use this if you put your certs on ./certs dir
    #     #secretName: tls-secrets

  scheduling:
    userScheduler:
      enabled: false
    podPriority:
      enabled: false
    userPlaceholder:
      enabled: false

  cull:
    enabled: true
    timeout: 3600
    every: 600

  proxy:
    chp:
      networkPolicy:
        enabled: false
    secretToken: <PUT HERE A RANDOM TOKEN openssl rand -hex 32>

  singleuser:
    networkPolicy:
          enabled: false
    storage:
      dynamic:
        storageClass: longhorn

  hub:
    image:
      name: dodasts/jupyterhub
      tag: '1.3.0-infncloud'
    cookieSecret: <PUT HERE A RANDOM TOKEN openssl rand -hex 32>
    networkPolicy:
      enabled: false
    args:
    - jupyterhub
    - --config
    - /etc/jupyterhub/jupyterhub_config.py
    - --upgrade-db
    db:
      type: sqlite-pvc
      upgrade:
      pvc:
        accessModes:
          - ReadWriteOnce
        storage: 1Gi
        storageClassName: longhorn
    extraEnv:
      OAUTH_CALLBACK_URL: https://jhub.<publicIP>.myip.cloud.infn.it/hub/oauth_callback
      OAUTH_ENDPOINT: https://iam-user.cloud.cnaf.infn.it/
      OAUTH_GROUPS: users
      ADMIN_OAUTH_GROUPS: admins
      WITH_GPU: "false"
    extraConfig:
      myConfig.py: |
        {{ .Files.Get "jub_config.py" | indent 6 }}
spark:
  enabled: false
