# Default values for Spark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ClusterRoleBinding parameters
clusterRoleBinding:
    name: default-pyspark
    namespace: default
    subjects:
        kind: User
        name: system:serviceaccount:default:default
        apiGroup: rbac.authorization.k8s.io
    roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io

# ExternalIps to be used for service exposition
externalIp:
    enabled: true
    ips: 192.168.65.3

# Spark master deployment and service configuration values
master:
    name: master
    namespace: default
    image: dodasts/spark-k8s-py
    imageTag: v2.0.0-rc1
    replicas: 1
    component: spark-master
    cpu: 100m
    memory: 1024Mi
    servicePort: 7077
    containerPort: 7077
    # Set Master JVM memory. Default 1g
    # DaemonMemory: 1g
    serviceType: NodePort
    jupyter:
        nodePort: 30888
        token: testme
        port: 8888
        image: dodasts/pyspark-notebook
        tag: v2.0.0-rc1


# WebUi service configuration values
webUi:
    name: webui
    namespace: default
    servicePort: 8080
    containerPort: 8080
    nodePort: 30808
    serviceType: NodePort

# Where to store jupyter data
hostPath:
    path: /tmp
