apiVersion: v1
kind: Service
metadata:
  name: hub-webui
  labels:
    component: "hub"
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: "hub"
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1 Ingress
kind: Ingress
metadata:
  name: hub-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"

spec:
  tls:
  - hosts:
    - "jhub.{{ .Values.hub.host }}.myip.cloud.infn.it"
    secretName: dash-selfsigned
  rules:
  - host: "jhub.{{ .Values.hub.host }}.myip.cloud.infn.it"
    http:
      paths:
      - path: /
        backend:
          serviceName: hub-webui
          servicePort: 8888