redis:
  image: 
    pullPolicy: IfNotPresent
    name: redis
    tag: 6.2.5
  requests: 
    cpu: 900m
    memory: 900M
  limits:
    cpu: 1
    memory: 1G
listener:
  image:
    pullPolicy: Always 
    name: dodasts/dask-ssh-listener 
    tag: v0.1.1
  requests: 
    cpu: 900m
    memory: 900M
  limits:
    cpu: 1
    memory: 1G
daskssh:
  image:
    pullPolicy: Always
    name: dodasts/dask-ssh-forwarder
    tag: v0.1.1
  nodePort: 31022
  requests: 
    cpu: 900m
    memory: 900M
  limits:
    cpu: 1
    memory: 1G
