{{- if .Values.master.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccb-pod
  labels:
    app.kubernetes.io/name: master
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: master
    spec:
      priorityClassName: system-node-critical
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - master
            topologyKey: kubernetes.io/hostname
      #hostNetwork: true
      containers:
      - name: ccb
        resources:
          requests:
            memory: {{ .Values.master.requests.memory }}
            cpu: {{ .Values.master.requests.cpu }}
        imagePullPolicy: {{ .Values.master.image.pullPolicy }}
        image: "{{ .Values.master.image.name }}:{{ .Values.master.image.tag | default .Chart.AppVersion }}"
        volumeMounts:
          - mountPath: "/etc/condor/config.d"
            name: configd
          - name: clustersecret
            mountPath: /etc/pwd
          - name: mapfile
            mountPath: /home/uwdir/
          - name: hostcerts
            mountPath: /etc/certs
      volumes:
      - name: hostcerts
        secret:
          secretName: example-com-tls
          defaultMode: 420
      - name: configd
        configMap:
          name: ccbconfigd
      - name: clustersecret
        secret:
          secretName: clustersecret
          defaultMode: 256
      - name: mapfile
        configMap:
          name: mapfile
  selector:
    matchLabels:
      app.kubernetes.io/name: master
  

  replicas: 1

{{- end }}