{{- if .Values.schedd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedd-pod
  labels:
    app.kubernetes.io/name: schedd
  annotations:
    configmap.reloader.stakater.com/reload: "scheddconfigd,mapfile"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: schedd
    spec:
      priorityClassName: system-node-critical
      #hostNetwork: true
      affinity:
{{- if .Values.schedd.affinity}}
{{ .Values.schedd.affinity  | indent 8 }}
{{- end }}
      hostAliases:                                                                                                           
      - hostnames:                                                                                                           
        - {{ .Values.schedd.hostname }}
        ip: {{ .Values.master.publicIP }}
      initContainers:
      - name: changeowner
        image: busybox
        command: ["sh", "-c", "chown -R 64 /var/lib/condor/spool"]   
        volumeMounts:
          - name: spool
            mountPath: /var/lib/condor/spool
      containers:
      - name: schedd
        resources:
          requests:
            memory: {{ .Values.schedd.requests.memory }}
            cpu: {{ .Values.schedd.requests.cpu }}
        imagePullPolicy: {{ .Values.schedd.image.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - CAP_SYS_ADMIN
          privileged: true
        image: "{{ .Values.schedd.image.name }}:{{ .Values.schedd.image.tag | default .Chart.AppVersion }}"
        volumeMounts:
          - mountPath: "/etc/condor/config.d"
            name: configd
          - name: spool
            mountPath: /var/lib/condor/spool
          #- mountPath: "/etc/ca"
          #  name: cafile
          - name: clustersecret
            mountPath: /etc/pwd
          - name: mapfile
            mountPath: /home/uwdir/
          - name: hostcerts
            mountPath: /etc/certs
{{- if .Values.nfs.enabled }}
          - mountPath: "{{ .Values.nfs.path }}"
            name: nfs
{{- end }}
      volumes:
      - name: configd
        configMap:
          name: scheddconfigd
      #- name: cafile
      #  configMap:
      #    name: cafile
      - name: clustersecret
        secret:
          secretName: clustersecret
          defaultMode: 256
      - name: hostcerts
        secret:
          secretName: htcondor-tls
          defaultMode: 420
      - name: mapfile
        configMap:
          name: mapfile
      - name: spool
        persistentVolumeClaim:
          claimName: spool
{{- if .Values.nfs.enabled }}
      - hostPath:
          path: "{{ .Values.nfs.path }}"
          type: Directory
        name: nfs
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: schedd

  replicas: 1
  strategy:
    type: Recreate
{{- end }}
